language: node_js
node_js:
  - node
services: mongodb

cache:
  directories:
    - node_modules

deploy:
  provider: lambda
  function_name: "task-b"
  region: "ap-southeast-1"
  role: "arn:aws:iam::540158443091:role/lambda-role"
  runtime: "nodejs14.x"
  handler_name: "handler"

script: 
  - npm test